spring.application.name=pos-lite
spring.profiles.active=dev

# JWT
app.jwt.secret=12345678901234567890123456789012
app.jwt.issuer=pos-lite
app.jwt.expMinutes=1440

#create admin invitation
admin.invite.code=d4ff94896ff6550ca226df1799c5bbf4