spring.datasource.url=jdbc:postgresql://localhost:5432/posdb
spring.datasource.username=posuser
spring.datasource.password=pospass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.cors.allowed-origins=http://localhost:5173

spring.security.user.name=admin
spring.security.user.password={noop}admin
spring.security.user.roles=ADMIN

spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.sql.init.encoding=UTF-8

# JWT
app.jwt.secret=12345678901234567890123456789012
app.jwt.issuer=pos-lite
app.jwt.expMinutes=120